Adding optional CPUID field in microarchitecture schema and in json file for Arm architectures
archspec/archspec-json pull request #110
Opened 2024-06-11 08:00 UTC by paolotricerri

As part of https://github.com/archspec/archspec/pull/168 on the archspec repo, it was decided to add, where it made sense for ARM cores a new field, called `cpuid` rather than adding a new submodule just for that.

These changes aim at:

 - adding the optional field in the microarchitecture_schema file 
 - introducing the field "cpuid" in the ARM microarchitectures 

This field will be used in the cpu/detect.py file in the archspec repo, for which a separate PR will be opened.

2024-07-04 10:25 UTC, paolotricerri commented
Sorry, didn't realise I had not tagged @alalazo in the review.

Thanks
P

2024-07-05 04:03 UTC, alalazo requested changes
Let's work on this one first, to get the detection based on `cpuid`/`cpupart` working. Then we can add `neoverse_n2` and deprecate the `neoverse_v2`  optional features.

2024-07-05 04:03 UTC, alalazo commented on cpu/microarchitectures.json
> +      "cpuid": "0x41d0c"
We already have the `vendor` field above, which if I understand correctly covers for the first part of the `cpuid` information (there's a mapping below in the file to go from hex code to vendor name). The second part seems to be the `cpupart`, i.e. `0xd0c`. If that's the case, can we just add that?

2024-07-08 09:39 UTC, paolotricerri commented on cpu/microarchitectures.json
> +      "cpuid": "0x41d0c"
You are right. I have replaced `cpuid` with `cpupart` and removed the `cpu implementer` part from the string. 

In the archspec repo, I'll apply the changes to deal with the `cpupart` field from the json.

2024-07-09 02:59 UTC, alalazo approved these changes
Thanks

2024-07-09 03:01 UTC, merged