N2 example
archspec/archspec-json pull request #112
Opened 2024-06-21 11:06 UTC by paolotricerri

This patch goes together with https://github.com/archspec/archspec/pull/170  . Similarly to that PR, this PR is intended to be a proposal on how to use the cpuid field to identify candidates on aarch64 architectures.

This patch introduces an example of neoverse_n2 example (in the test folder) and the neoverse_n2 in the microarchitectures.json. The addition in the json file would overwrite https://github.com/archspec/archspec-json/pull/105 but, as this PR is intended to be a proposal, I'll carefully manage it if PR#105 gets merged in first.

Warning: This patch has not removed the SM crypto features from the neoverse_v2 definition yet.

CC: @dslarm, @alalazo

2024-07-04 10:24 UTC, paolotricerri commented
Hi @alalazo, I was wondering if you have had the time to have a look at the proposal? 

Thanks
P

2024-07-05 03:41 UTC, alalazo requested changes

2024-07-05 03:41 UTC, alalazo commented on tests/targets/linux-rhel9-neoverse_n2
> +CPU revision    : Irrelevant
Can you add back the "Irrelevant" parts? It would be good to maintain a real sample of a system, so that if we start using other info we don't have to rework all test data.

2024-07-05 03:41 UTC, alalazo commented on cpu/microarchitectures.json
> +      "cpuid": "0x41d08"
Q: Are we considering the `cpuid` field on ARM required or optional ? In the former case I see it's missing on some uarchs.

2024-07-08 09:41 UTC, paolotricerri commented on tests/targets/linux-rhel9-neoverse_n2
> +CPU revision    : Irrelevant
I will add them. Your point makes sense to me. Was just trying to clearly indicate what was not necessary for the test.

2024-07-08 09:42 UTC, paolotricerri commented on cpu/microarchitectures.json
> +      "cpuid": "0x41d08"
We want to keep the cpuid (cpupart now, see https://github.com/archspec/archspec-json/pull/110#discussion_r1668320616 ) optional as all the necessary info might be easily available for old cores.

2024-07-09 03:04 UTC, alalazo commented
I assume this one supersedes #105, so let's continue working here. Can you rebase? Other than that this looks fine.

2024-07-09 12:52 UTC, paolotricerri commented
HI @alalazo , have rebased and pushed to the branch. 

Thanks

2024-07-09 12:55 UTC, alalazo submitted a review, later dismissed

2024-07-09 12:57 UTC, alalazo commented on cpu/microarchitectures.json
> +      "cpuid": "0xd49"
```suggestion
      "cpupart": "0xd49"
```
?

2024-07-09 12:59 UTC, merged