Added architecture flag znver3 for AOCC compiler 3.0 and above
archspec/archspec-json pull request #25
Opened 2021-03-10 06:47 UTC by amd-toolchain-support

march and mtune flangs are added for znver3 when AOCC 3.0 or above compiler is used.

2021-03-10 07:09 UTC, tgamblin commented
LGTM!  Thanks!  Any chance gcc and clang could also be added here?

2021-03-10 08:14 UTC, alalazo requested changes
Thanks a lot for the contribution!

I see that `znver3` has the same features as `zen2`. Is that correct or does it need to be complemented with new features? Also, it would be good to have a sample `/proc/cpuinfo` for regression tests.

2021-03-10 08:14 UTC, alalazo commented on cpu/microarchitectures.json
> +      ],
Can you also provide a sample `/proc/cpuinfo` under the `test/targets` directory?

2021-03-10 15:17 UTC, alalazo commented on cpu/microarchitectures.json
> +      ],
> Is the file '/proc/cpuinfo' file mandatory for this pull request to be accepted?

I'd say highly recommended. Without that it's impossible for `archspec` or other bindings (if there will be in the future) to unit test the detection of the architecture. Dumping the information from a single processor in a file named `linux-<os>-znver3` is fine. There are other examples under `tests/targets`

> Are you looking for the 'flags' section or any other specific section of the 'proc/cpuinfo' file, please let us know what you are looking for in this file

Any feature in the flags section of `/proc/cpuinfo` that may influence a binary executable. For other architectures we usually get those from GCC man pages, for instance for haswell the interesting flags are:
```
haswell
               Intel Haswell CPU with 64-bit extensions, MOVBE, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, POPCNT, AVX, AVX2, AES, PCLMUL,
               FSGSBASE, RDRND, FMA, BMI, BMI2 and F16C instruction set support.
```

The list you have now is "wrong" in the sense that it is very likely incomplete. Having the same set of flags as `zen2` means that any `zen2` uarch would be detected as `zen3` if this PR gets merged as is. Let me know if this needs clarification.

2021-03-10 15:37 UTC, GaneshPrasadMA commented on cpu/microarchitectures.json
> +      ],
Thanks for the explanation, please note that I will get back to you on the same

2021-03-12 15:40 UTC, GaneshPrasadMA commented on cpu/microarchitectures.json
> +      ],
The above review comments have been addressed, kindly request for your review

2021-03-12 17:49 UTC, tgamblin requested changes

2021-03-12 17:49 UTC, tgamblin commented on tests/targets/linux-ubuntu20.04-znver3
> +power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
@GaneshPrasadMA: we should only need one of the /proc/cpu records (as they're all pretty much the same).  Can you cut out the parts for procs 1-31 and leave just 0?

2021-03-12 18:07 UTC, GaneshPrasadMA commented on tests/targets/linux-ubuntu20.04-znver3
> +power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
Please note that I have addressed the above review comment, and request for further review.

2021-03-12 19:45 UTC, alalazo commented
@GaneshPrasadMA Thanks for the changes. I'll try to submit a draft PR in archspec based on this branch. If tests pass on that PR this would be fine with me. Otherwise I'll report the issues.

2021-03-12 21:54 UTC, tgamblin commented on tests/targets/linux-ubuntu20.04-znver3
> +power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
Thanks Ganesh1

2021-03-13 02:51 UTC, GaneshPrasadMA commented
Yes, please report issues if any so that we can try to fix them.
I sincerely seek your guidance on the same as I am handling this magnitude of change in archspec for the first time.

2021-03-13 10:47 UTC, alalazo requested changes
@GaneshPrasadMA There's one just typo I induced you into. Can you please rename `linux-ubuntu20.04-znver3` into `linux-ubuntu20.04-zen3`? This is needed for unit test discovery in archspec. After that is done I think this is ready to be merged.

2021-03-13 14:34 UTC, GaneshPrasadMA commented
Thanks for pointing that out. It has been corrected and changes as per the review comment have been pushed.

2021-03-13 15:44 UTC, alalazo approved these changes

2021-03-13 15:47 UTC, merged

2021-03-13 15:47 UTC, alalazo commented
Thanks @GaneshPrasadMA !