Add support for microarchitecture levels
archspec/archspec-json pull request #31
Opened 2021-05-11 15:59 UTC by pikacic

This introduces definitions for the [microarchitecture levels](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels):
- `x86-64-v2` (basically an alias to `nehalem` with generic tuning)
- `x86-64-v3` (alias to `haswell` with generic tuning)
- `x86-64-v4` (alias to `skylake_avx512` with generic tuning)

I also implemented equivalent compiler flags for gcc < 11.1 and clang < 12.0.

It's my first PR pm archspec, so I have some doubts about how to tune the compiler version ranges and the features list.

Resolves archspec/archspec-json#30

2021-05-11 16:14 UTC, pikacic commented on cpu/microarchitectures.json
> +      "features": [
technically one should add `cx16` and `lahf_lm` to the features list of all microarchitectures that derive from `x86-64-v2` (I'm not 100% sure `nehalem` has those features, but they are available in [all modern x86-64 CPUs](https://en.wikipedia.org/wiki/X86-64#Older_implementations))

2021-05-11 16:14 UTC, pikacic commented on cpu/microarchitectures.json
> +            "versions": "4.6:10.3",
which is the correct way of specifying `gcc < 11.1`? Should I use the latest known `10.x` version or a dummy `10.99`?

2021-05-11 16:54 UTC, tgamblin commented
I think we should break the tie by detecting the actual architecture.  In some cases the feature lists are tweaked so that we can detect on cloud nodes and VMs, where certain features are disabled.  But we still know with very strong likelihood that, e.g., the chip is a `haswell`. 

`x86-64-v3` is virtual -- i.e. there isn't actually a microarchitecture called that, and I think users will want detection to return the actual chip name.  We can still say that `x86-64-v3` is compatible with `haswell` (but shouldn't do vice versa due to the instructions you mention).

2021-05-11 16:55 UTC, tgamblin commented
I think the above actually works out pretty well in the implementation -- arch spec will take the "highest" architecture in the DAG that has the features of the host.  If `haswell` inherits from `x86-64-v3`, it'll always be preferred in detection.

2021-05-12 01:11 UTC, bartoldeman commented on cpu/microarchitectures.json
> +      "features": [
`lahf_lm` and `cx16` (cmpxchg16b) are not available in some early 64bit chips, but you need to go quite a long way back, further than Nehalem. For cx16 all the way back to the Core 2, and for lahf to the Pentium 4 and some early AMD Athlons.

2021-05-12 06:03 UTC, tgamblin requested changes
@pikacic: This looks great to me, modulo the version question you asked.  Can you address that?

@alalazo can you give this a look?  If it's ok with you I think it's good to go.

2021-05-12 06:24 UTC, boegel commented
> @boegel we don't currently have aliases, and the names are pretty much set by gcc and clang -- it's in the ABI spec now. I think we can add aliases later if we grow a feature. I want to do that so that so that `rome`, `milan`, `genoa` eventually map to `zen2`, `zen3`, `zen4`, etc.

Makes sense, `x86_64-avx` (or just `avx`) as an alias for a virtual microarchitecture makes sense.

2021-05-12 06:28 UTC, tgamblin commented
> Makes sense, x86_64-avx

I generally prefer dashes to `_` and almost asked for it in this PR, but we made a conscious decision to use `_` in arch spec so that the names would fit unambiguously in hyphenated arch strings (e.g. `x86_64_avx-linux-gnu`)

2021-05-12 08:03 UTC, alalazo commented on cpu/microarchitectures.json
> +      "from": ["x86_64_v2"],
I wonder if:
```suggestion
      "from": ["core2", "x86_64_v2"],
```
is a better modeling choice (and similarly for the other virtual versions below). Need to give some more thought at it.

2021-05-12 08:05 UTC, alalazo requested changes
Thanks a lot, this looks great! I am just marking a request for change to be sure:
- We go through the comment on inheritance I left above
- We test these changes in a branch of the archspec library before merging them

2021-05-12 08:27 UTC, pikacic commented on cpu/microarchitectures.json
> +            "versions": "4.6:10.3",
Done, although GCC 11.0 does not exist (it looks like they have been skipping the `x.0` tag recently).
What about Clang?

2021-05-12 08:53 UTC, tgamblin commented on cpu/microarchitectures.json
> +            "flags": "-march={name} -mtune=generic"
Just curious on this -- is it possible to do this:

```
-march=x86-64-v3 -mtune=x86-64-v3
```

And does the tuning option do anything different from what `generic` would?

2021-05-12 09:29 UTC, pikacic commented on cpu/microarchitectures.json
> +            "flags": "-march={name} -mtune=generic"
It's not possible, from GCC doc:

> Since these _cpu-type_ values do not have a corresponding `-mtune` setting, using `-march` with these values enables generic tuning. Specific tuning can be enabled using the `-mtune=other-cpu-type` option with an appropriate *other-cpu-type* value.

I was even reluctant to add `-mtune=generic` as it's implicit, but I understood the policy is to always add a `-mtune` flag even when it's not needed.

2021-05-18 17:43 UTC, tgamblin commented
@alalazo is there more left to do here?  It would be good to have more tests, but if this works with archspec right now I'm tempted to say we should merge it.  Can you try it out?

2021-05-18 18:16 UTC, alalazo commented
@tgamblin Will do by tomorrow. Do we have any preference on this https://github.com/archspec/archspec-json/pull/31#discussion_r630815172 ? 

Basically right now we have:
```
nehalem
  |
core2
  |
[ ... ]
```
This PR makes it like:
```
nehalem
  |
x86-64-v2 (virtual)
  |
core2
  |
[ ... ]
```
I'm tempted to say it would be better to branch in like:
```
nehalem
  |       \
core2   x86-64-v2 (virtual)
  |
[ ... ]
```

2021-05-18 19:56 UTC, pikacic commented
@alalazo, something like
```
nehalem
  |       \
core2   x86-64-v2 (virtual)
  |
[ ... ]
```
hides the fact that `x86-64-v2` can run `core2` binaries. I would prefer
```
nehalem
  |     \
  |      x86-64-v2 (virtual)
  |     /
core2   
  |
[ ... ]
```

2021-05-19 08:57 UTC, alalazo commented
@pikacic @tgamblin I'm reading the documents more closely and my understanding is that the modeling here is currently incorrect, since it adds properties to what is in the definitions of the virtual levels. For instance in this PR we have `x86_64_v3` inherit from `ivybridge` but that seems wrong since in the virtual levels I don't see mentioned, for instance, `AES` or `FSGSBASE` or `RDRAND` etc. that `ivybridge` has according to GCC docs.

As per https://github.com/archspec/archspec-json/pull/31#issuecomment-843416872 I think a better modeling would be to:
1. Have all the virtual levels inherit from each other (x86_64 -> x86_64_v2 -> etc.)
2. Keep the virtual levels separated from "real" uarchs (i.e. no branches from a real uarch to a virtual level)
3. Branch-in as suggested on the first uarch that supports that virtual level

I suggest point 2 specifically since, by reading the documents, it doesn't seem the virtual levels are only for Intel so it would be good to keep them separated from the vendors - since they could also branch into AMD procs?

> hides the fact that x86-64-v2 can run core2 binaries. I would prefer

That would be true for `core2` but not for other uarchs, if my understanding is correct. So I would not special case `core2` just for that for the reason explained above.

Let me know if I missed or misunderstood any point.

2021-05-19 11:50 UTC, pikacic commented
@alalazo, I think now I understand a bit better the archspec architecture and I agree completely with your suggestion.
Give me a few minutes to implement it.

2021-05-19 12:45 UTC, pikacic commented
It took me a bit longer than expected because I tweaked a bit the flags to match a bit better the instructions enabled by the uarch levels.

With the latest change (if I understand correctly how this all works) the `x86-64-vX` architectures will not be matched when detecting the CPU uarch (somehow as before). The DAG is such that when a binary is built for `x86-64-v3` we can run it on `haswell` (or more recent) CPUs.

I also declared the compatibility of AMD CPUs with the new microarchitecture levels (deduced from [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html)).

@alalazo, @tgamblin, can you check, please?

2021-05-19 13:09 UTC, alalazo commented
I'll have a look at this asap and try it in `archspec`. One minor request for the layout of the JSON file: can we have the definitions for the virtual levels directly below the `x86_64` definition?

2021-05-19 13:11 UTC, pikacic commented
I couldn't decide if to have them grouped at the beginning or at the end, so I kept them interleaved.
I'll move them right away... and let me know if you want me to squash the commits.

2021-05-19 13:13 UTC, alalazo commented
> I'll move them right away... and let me know if you want me to squash the commits.

No worries. We'll squash merge the PR in the end :slightly_smiling_face:

2021-05-19 13:23 UTC, alalazo commented
Thanks @pikacic I'll double check the entries and add a draft PR in archspec. I'll get back here as soon as I have news.

2021-05-20 13:01 UTC, alalazo commented
@pikacic I think `zen` can derive from `x86_64_v3` directly instead of `x86_64`.

2021-05-20 14:13 UTC, pikacic commented
@alalazo, you are right... I missed that `zen` was not compatible with `excavator`.

I also changed the compatibility list of `bulldozer`, as `["x86_64", "x86_64_v2"]` was not particularly useful.

2021-05-20 14:21 UTC, alalazo commented
@pikacic Thanks! This looks great to me!

2021-05-20 14:42 UTC, alalazo commented
For reference, once this is merged I'll update https://github.com/archspec/archspec/pull/51

2021-05-20 14:50 UTC, tgamblin approved these changes

2021-05-20 14:50 UTC, tgamblin commented
LGTM!

2021-05-20 14:50 UTC, tgamblin commented
Thanks @pikacic!

2021-05-20 14:53 UTC, merged