Add oneapi compiler
archspec/archspec-json pull request #47
Opened 2022-05-20 18:15 UTC by glennpj

This PR adds the oneapi and dpcpp compilers to archspec. These compilers
are Intel's latest generation compilers and have similar options to the
classic Intel compilers. As such, the entries here are based on the
intel entires.

Note: I also added entries, including for intel, to the zen3 block. If
there was a reason that the intel compiler was not there then the new
entries in that section will need to be removed.

2022-05-20 18:35 UTC, glennpj commented
I think I have fully corrected my copy/paste error.

2022-05-20 18:50 UTC, alalazo requested changes
If you want to run it locally:
```console
$ jsonschema -i cpu/microarchitectures.json cpu/microarchitectures_schema.json
```

2022-05-20 19:15 UTC, glennpj commented
Yea, I still have something wrong in there.

2022-05-20 21:19 UTC, glennpj commented
I can patch spack to get it to ignore the two toolchains. So, I think this PR is ready and spack will need a separate PR.

@alalazo Let me know how you want to coordinate that. I guess there is no point in patching spack until this is picked up by it.

2022-05-23 10:10 UTC, alalazo approved these changes
Thanks @glennpj !

2022-05-23 10:11 UTC, merged