Added Graviton3 as target architecture
archspec/archspec-json pull request #53
Opened 2022-06-06 13:26 UTC by OliverPerks

I think I have a 'good' set of architecture flags for the different compilers. Some may be missing, happy to iterate if we want to check any.

2022-06-06 13:27 UTC, OliverPerks commented
Sorry, only just seen #51 - This one adds the 'correct' flags.

2022-06-07 07:41 UTC, boegel commented
This looks way more mature than my PR #51, so I'll close that.

@alalazo Do we have a procedure in place to check/accept PRs like this?

2022-06-07 08:27 UTC, alalazo requested changes
Can you add a sample of `/proc/cpuinfo` in the `tests/targets` directory? That will allow us to test detection of `graviton3`

2022-06-07 08:33 UTC, OliverPerks commented
@alalazo - Sorry forgot to add that file. Done now.

2022-06-07 08:38 UTC, alalazo commented on cpu/microarchitectures.json
> +          "evtstrm",
```suggestion
	  "fp",
          "asimd",
          "evtstrm",
```

2022-06-07 10:32 UTC, alalazo approved these changes
LGTM. Just want to double check one thing: is it correct to root each `gravitonX` to `aarch64` instead of having:
```
aarch64 -> graviton -> graviton2 -> graviton3
```
? I think the question is, can we say that a binary optimized for `gravitonX` can always run on `gravitonY` fot `X <= Y`?

2022-06-07 11:04 UTC, OliverPerks commented
That is a good question. In theory Graviton X could have a feature Graviton X+1 doesn't support, but in practice they are strict subsets.

2022-06-07 11:21 UTC, alalazo approved these changes

2022-06-07 11:22 UTC, merged

2022-06-07 11:23 UTC, alalazo commented
Thanks @OliverPerks