Remove `umip` feature from icelake
archspec/archspec-json pull request #54
Opened 2022-07-06 15:12 UTC by stephenmsachs

This feature is not exposed in virtualized environments, e.g. icelake based AWS EC2 instances.

With the `umip` flag in place there is no way to identify icelake based
instances correctly form within Archspec and the next alternative x86_64_v4 is
too wide for proper optimization.

2022-07-07 14:16 UTC, tgamblin commented
We need to also add arguments so that compilers will not emit this instruction.

2022-07-07 14:57 UTC, alalazo requested changes
On top of what @tgamblin says, there's also `cannonlake` that can emit `umip` according to GCC `man` page. Which instructions are you seeking that are in `icelake` and not in `x86_64_v4`?

2022-07-08 14:04 UTC, stephenmsachs commented
> Which instructions are you seeking that are in icelake and not in x86_64_v4`?

This is not only about instructions. Current (and future) Intel compilers can use heuristics and make assumptions based on other CPU feature like cache sizes or latency. They will not be able to make those same assumptions with the ABI version as it is too wide.

> We need to also add arguments so that compilers will not emit this instruction.

This cpu Flag is different than ones like avx which are placeholders to enable/disable a set of instructions. The [Intel® 64 and IA-32 Architectures Software Developer’s Manual](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html) says:

> CR4.UMIP
> User-Mode Instruction Prevention (bit 11 of CR4) — When set, the following instructions cannot be executed if CPL > 0: SGDT, SIDT, SLDT, SMSW, and STR. An attempt at such execution causes a general- protection exception (#GP).

Here CPL is the ring, so if `umip` is *enabled* any call to those instructions from user-mode will result in an exception. We have `umip` *disabled* in those icelake EC2 instances. Furthermore, these calls are emulated by the kernel since [4.15 release](https://elixir.bootlin.com/linux/v4.15/source/arch/x86/kernel/umip.c), so a application would not see any difference anyway.

> there's also cannonlake that can emit umip according to GCC man page.

Yes, I will remove it for cannonlake as well.

2022-07-15 13:45 UTC, alalazo approved these changes

2022-07-15 13:46 UTC, merged