remove x86-64 from intel classic compiler
archspec/archspec-json pull request #56
Opened 2022-10-03 03:08 UTC by simonleary-umass-edu

`x86-64` is nowhere in [the intel classic compiler manual section on the `march` flag](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/code-generation-options/march.html). 

```
/modules/spack-0.18.1/lib/spack/env/intel/icc -fPIC -O2 -D_LARGEFILE64_SOURCE=1  -c -o adler32.o adler32.c
icc: command line warning #10148: option '-march=x86-64' not supported
```

This should probably be fact checked on a system that isn't mine.

2022-10-10 07:41 UTC, tgamblin requested changes
@alalazo do you agree?

2022-10-10 07:41 UTC, tgamblin commented on cpu/microarchitectures.json
> -        ],
pentium4 is the equivalent on Intel compilers -- so I think this should be:

```json
        "intel": [
           {
             "versions": ":",
             "name": "pentium4",
             "flags": "-march={name} -mtune=generic"
           }
         ],
```

`pentium4` is also the default for Intel compilers (at the moment at least), but we want to always set an arch flag to ensure that we restrict the used instructions.

2022-10-10 07:49 UTC, alalazo commented on cpu/microarchitectures.json
> -        ],
If I recall correctly I submitted this PR https://github.com/archspec/archspec-json/pull/48 out of a conversation with @rscohn2 Let me check if I can find the issue in Spack.

2022-10-10 08:16 UTC, alalazo commented on cpu/microarchitectures.json
> -        ],
I can't find the conversation yet, but I checked with different version of the Intel compilers and confirm that this line needs to be reverted to `pentium4` as @tgamblin says. @rscohn2 let us know if there's more to that.

2022-10-10 12:55 UTC, rscohn2 commented
I believe there was a slack discussion, but I don't know how to find it.

The problem I reported was that the oneapi compilers do not accept ``pentium4``:
```
(venv) rscohn1@rscohn1-mobl1:compilers$ icpx -march=pentium4 ~/local/projects/spack/meson-project/cpp/main.cpp -c
error: unknown target CPU 'pentium4'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont,
      gracemont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell,
      common-avx512, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server,
      tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3,
      amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3,
      x86-64-v4
(venv) rscohn1@rscohn1-mobl1:compilers$
```

The classic compilers accept pentium4, but not x86-64

2022-10-10 12:58 UTC, rscohn2 commented
By the way, I just noticed that the latest classic compiler release has a deprecation message:

```
(venv) rscohn1@rscohn1-mobl1:compilers$ icc -march=x86-64 ~/local/projects/spack/meson-project/cpp/main.cpp -c
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second hal\
f of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this co\
mpiler. Use '-diag-disable=10441' to disable this message.
```

Is there something I should do to expose this to spack users?

2022-10-17 14:44 UTC, alalazo approved these changes

2022-10-17 14:46 UTC, merged