Rename graviton product with ARM uarch name
archspec/archspec-json pull request #57
Opened 2022-10-09 09:57 UTC by alalazo

refers #41 

Modifications:
- [x] Change the name of the Graviton products to corresponding generic ARM uarch names
- [x] Rename test files accordingly

2022-10-09 10:19 UTC, alalazo commented
@tgamblin So far the PR just does the renaming, and adjusts some flags. I'll check how to add generic architecture levels next (either in this PR or in another).

2022-10-09 11:55 UTC, alalazo commented on cpu/microarchitectures.json
> +            "versions": ":",
The versions for both `arm` and `apple-clang` need to be checked, but I guess we can do that in a follow up PR. The versions for `gcc` and `clang` should be correct, but maybe stricter than necessary - they can also be refined later.

2022-10-10 06:37 UTC, boegel requested changes

2022-10-10 06:37 UTC, boegel commented on cpu/microarchitectures.json
> +	      "fp",
unintended indent?

2022-10-10 06:37 UTC, boegel commented on cpu/microarchitectures.json
> -                  "flags" : "-march=armv8.4-a+crypto+rcpc+sha3+sm4+sve+rng+ssbs+i8mm+bf16+nodotprod -mtune=neoverse-v1"
Why drop the `-march` part?

2022-10-10 06:58 UTC, alalazo commented on cpu/microarchitectures.json
> -                  "flags" : "-march=armv8.4-a+crypto+rcpc+sha3+sm4+sve+rng+ssbs+i8mm+bf16+nodotprod -mtune=neoverse-v1"
Because of this https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu

2022-10-10 07:03 UTC, alalazo commented on cpu/microarchitectures.json
> +	      "fp",
Thanks for catching. It turned out there was a spurious tab added in the graviton3 PR. The tab looked unindented in my IDE. Now they're all spaces.

2022-10-10 07:48 UTC, boegel commented on cpu/microarchitectures.json
> -                  "flags" : "-march=armv8.4-a+crypto+rcpc+sha3+sm4+sve+rng+ssbs+i8mm+bf16+nodotprod -mtune=neoverse-v1"
Maybe it's worth adding that link somewhere, maybe in the README file in this repo?

2022-10-10 08:00 UTC, alalazo commented on cpu/microarchitectures.json
> -                  "flags" : "-march=armv8.4-a+crypto+rcpc+sha3+sm4+sve+rng+ssbs+i8mm+bf16+nodotprod -mtune=neoverse-v1"
Sure, we might start another doc related PR and add more generally a section on "resources" to look at when adding a new compiler.

2022-10-12 20:37 UTC, tgamblin approved these changes
This LGTM.  We likely need to add aliases either on the spack side or within `archspec` python, so that the binaries continue to work.

2022-10-17 15:04 UTC, alalazo commented on cpu/microarchitectures.json
> +      "from": ["neoverse_n1"],
```suggestion
      "from": ["neoverse_n1", "armv8.4a"],
```

2022-10-17 15:06 UTC, alalazo commented
@boegel Can you re-review? Is there something missing?

2022-10-17 17:42 UTC, boegel approved these changes
No strong objections for my side.
This will obviously impact projects which are currently assuming that archspec will produce values like `graviton2` rather than `neoverse_n1`, so we should make it very clear in the release notes for the next `archspec` release that includes these changes...

2022-10-17 21:55 UTC, merged